CREATE DATABASE cartas;
USE cartas;

CREATE TABLE Usuario (
IDUsuario INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR (100)
);

CREATE TABLE Administrador (
IDUsuario INT PRIMARY KEY,
FOREIGN KEY (IDUsuario) REFERENCES Usuario (IDUsuario)
);

CREATE TABLE Jugador (
IDUsuario INT PRIMARY KEY,
Contra VARCHAR(255),
FOREIGN KEY (IDUsuario) REFERENCES Usuario (IDUsuario)
);

CREATE TABLE Partida (
IDPartida INT AUTO_INCREMENT PRIMARY KEY,
FechaHora DATETIME,
Ganador Varchar(100)
);

CREATE TABLE Juega (
IDUsuario INT,
IDPartida INT,
PRIMARY KEY (IDUsuario, IDPartida),
FOREIGN KEY (IDUsuario) REFERENCES Usuario (IDUsuario),
FOREIGN KEY (IDPartida) REFERENCES Partida (IDPartida)
);

CREATE TABLE Mano (
IDMano INT AUTO_INCREMENT PRIMARY KEY,
IDUsuario INT,
IDPartida INT,
FOREIGN KEY (IDUsuario, IDPartida) REFERENCES Juega (IDUsuario, IDPartida)
);

CREATE TABLE Carta (
IDCarta VARCHAR (3) PRIMARY KEY,
URL_Imagen VARCHAR (100),
Palo Varchar (10),
Numero TINYINT
);

CREATE TABLE Contiene (
IDCarta VARCHAR (3),
IDMano INT,
PRIMARY KEY (IDCarta, IDMano),
FOREIGN KEY (IDCarta) REFERENCES Carta (IDCarta),
FOREIGN KEY (IDMano) REFERENCES Mano (IDMano)
);